title: Bulk Delete Documents
description: This is an Add-On that deletes large batches of documents. Use with great caution as it is irreversible. 
instructions: ''
type: object
documents:
  - query
properties:
  confirm:
    title: Please select this box to confirm you want to irreversibly delete these documents
    type: boolean
categories:
  - bulk
version: 2
