title: Bulk Delete Documents
description: This is an Add-On that deletes large batches of documents. Use with great caution as it is irreversible. 
type: object
documents:
  - query
properties: {}
version: 2
